FILESEXTRAPATHS:prepend := "${THISDIR}/files:"
FILESEXTRAPATHS:prepend := "${THISDIR}/${PN}:"


SRC_URI += "file://0001-add-some-rules-to-our-gitignore.patch"
SRC_URI += "file://0002-Script-De-Automa-ao-de-Build-UBoot.patch"
SRC_URI += "file://0003-Inclus-o-do-comando-para-compila-o-do-stm32mp157f-dn.patch"
SRC_URI += "file://0004-Arquivo-de-configura-o-do-para-o-modulo-board-file-..patch"
SRC_URI += "file://0005-Corre-o-erro-de-digita-o.patch"
SRC_URI += "file://0006-cria-ao-de-arquivos-BSP-para-o-SOM-do-dn-lse.patch"
SRC_URI += "file://0007-fixe-mistakes-in-file.patch"
SRC_URI += "file://0008-Change-the-config-to-based-on-CPU-not-board-stm32mp1.patch"
SRC_URI += "file://0009-fixes-to-bug-that-not-start-the-board-when-the-kerne.patch"
SRC_URI += "file://0010-corrigir-o-bug-do-ftd.patch"
SRC_URI += "file://0011-Correction-of-function-int-board_late_init-void.patch"
SRC_URI += "file://0012-ATUALIZACAO-DO-SCRIPT-DE-BUILD.patch"
SRC_URI += "file://0013-CORRE-O-DO-TAMANHO-DA-PALAVRA-A-SER-DESCARTADA-PARA-.patch"
SRC_URI += "file://0014-Cria-o-do-board.h-para-gerenciamanto-das-nossas-vari.patch"
SRC_URI += "file://0015-fixing-up-all-bugs-around-of-som.patch"
SRC_URI += "file://0016-add-files-of-model-single-core-stm32mp151c-fom-DN-LS.patch"
SRC_URI += "file://0017-Configura-es-com-DTS.patch"
SRC_URI += "file://0018-USE-UART-TPD.patch"
SRC_URI += "file://0019-add-update-var.patch"
